on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build"
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   pull-requests: write
    #   repository-projects: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.3"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.3.1"
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build apk --debug
      - run: mkdir builds
      - run: mv build/app/outputs/apk/release/app-release.apk builds/app-release.apk
      - run: mv build/app/outputs/apk/debug/app-debug.apk builds/app-debug.apk
      - name: Push Test Build
      # - run: flutter pub get
      # - run: mkdir releaseBuilds
      # - run: flutter build apk --split-per-abi
      # - run: flutter build apk --release --split-per-abi
      # - run: flutter build apk --dart-define-from-file devEnv.json
      # - run: flutter build appbundle --dart-define-from-file devEnv.json
      # - run: mv build/app/outputs/apk/release/app-release.apk releaseBuilds/Personal-Expense-Tracker.apk
      # - run: mv build/app/outputs/bundle/release/app-release.aab releaseBuilds/BAV_Dev.aab
      # - run: flutter clean
      # - run: flutter build apk --split-per-abi
      # - run: flutter build apk --dart-define-from-file prodEnv.json
      # - run: flutter build appbundle --dart-define-from-file prodEnv.json --build-name=2.0.0 --build-number=8
      # - run: mv build/app/outputs/apk/release/app-release.apk releaseBuilds/Personal-Expense-Tracker.apk
      # - run: mv build/app/outputs/apk/release/app-release.apk releaseBuilds/BAV_Prod.apk
      # - run: mv build/app/outputs/bundle/release/app-release.aab releaseBuilds/BAV_Prod.aab
      - name: Push Test Build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
